name: Build & Deploy
on: 
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name:  Build step
        run: echo "Building the application"
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: deploy job
       run: echo "deploying the job"
